### ISSUE TITLE
Figma checken

### ISSUE THREAD

**Issue by cnoss** [th-koeln/mi-bachelor-screendesign#1]
- Was kann die aktuelle Version, gerade bezogen auf die Patternlab Systematik.
- Können wir Figma als TH weiterhin nutzen.
- Gäbe es Alternativen, gerade für Window?

**Comment by JulianSchoem** [comment]
Es gibt seit einem der letzten Updates nun auch in Figma mehr Möglichkeiten zu Material Design mit der Einbindung von "Styles":

https://blog.figma.com/material-design-figma-styles-98a7f0e2735e

https://help.figma.com/properties-panel/styles

Ich teste es direkt mal aus. Sketch Symbols gab es als "Components" schon länger in Figma und auch auch recht gut funktioniert.

Ein Patternlab zu erstellen scheint auf alle Fälle möglich zu sein:

https://blog.figma.com/material-design-figma-styles-98a7f0e2735e#7b4b

**Comment by vschaefer** [comment]
Zur zweiten Frage:
Für Studenten ist die Nutzung kostenlos.
Siehe: https://www.figma.com/education/
Man muss sich dazu einmal registrieren bei Figma und sich dann als Student verifizieren (siehe Screenshot).
![schnappschuss 2018-09-26 17 53 47](https://user-images.githubusercontent.com/2872395/46092415-204da180-c1b5-11e8-85cc-3ed05a421666.jpg)

**Comment by vschaefer** [comment]
Zu Frage 3:
Affinity Designer wäre eine Alternative, die es mittlerweile auch für Windows gibt.
Die bieten auch Education Lizenzen an
https://affinity.serif.com/de/education/

**Comment by JulianSchoem** [comment]
Als ich versucht habe, meinen Account zu einem Student Account umzuwandeln wurde meine Verifikation nicht akzeptiert:

> Your application to use Figma for free as a student has been denied. If you are a full-time student at an accredited institution and believe this is an error, please reach out to support@figma.com.

Ich habe den Support dann angeschrieben und diese Antwort bekommen. Nun funktioniert die Anmeldung auch mit School name "TH Köln".

> Thanks for writing us. I'm sorry you were having trouble upgrading to a student account. The reason your application is getting denied is because your school was not included in our database of accepted educational institutions that are eligible for a free Student account.
> 
> However, I have verified that your school does meet the minimum requirements for the free account, and I've added your school to our list!

**Comment by JulianSchoem** [comment]
Hi @cnoss  . Zu der Frage gestern in der Mensa wegen Figma: Account erstellen benötigt nur eine Email, Passwort und den Namen und schon ist der Free Account erstellt. Die Studenten können also direkt starten und es gibt sogar ein Google Material Design Projekt defaultmäßig angelegt. 
Die Studenten sollten dann am besten direkt die TH-Mail nutzen, damit die Education Version später keine Probleme macht. Die Verifizierung davon sollte nun aber auch nur noch 1-2 Minuten dauern bis man die Bestätigung per Mail erhält.

**Comment by JulianSchoem** [comment]
Da wir zur Klärung mit den Lizenzen bei Figma das Issue #14 haben, kann dieses Issue eigentlich geschlossen werden.
