### ISSUE TITLE
Niveaustufen auf Verständlichkeit prüfen

### ISSUE THREAD

**Issue by cnoss** [th-koeln/mi-bachelor-screendesign#10]
https://th-koeln.github.io/mi-bachelor-screendesign/niveaustufen/

**Comment by JulianSchoem** [comment]
Korrektur gelesen und korrigiert.

```
artefakt2:
name: Designkonzept als Mockup
 anteil: 2/2
```

Die anderen drei Abgabeteile sind jeweils 1/5. Somit habe ich das "Designkonzept als Mockup" zu 2/5 geändert.

**Comment by cnoss** [comment]
danke
