### ISSUE TITLE
Projektinfos gegenlesen

### ISSUE THREAD

**Issue by cnoss** [th-koeln/mi-bachelor-screendesign#20]
Hi, hab mal die Projektinfos komplettiert ... mit leicht betrunkenem Kopf (hüstl). Könntet ihr da mal drüber lesen und korrigieren?
https://th-koeln.github.io/mi-bachelor-screendesign/projekt-2018/

**Comment by christianh92** [comment]
Hab einmal durchgewischt und die Rechtschreibfehler rausgeworfen ;)
