### ISSUE TITLE
Designtools für Screendesigner raus suchen

### ISSUE THREAD

**Issue by cnoss** [th-koeln/mi-bachelor-screendesign#32]
Hi,

ich bräuchte noch mal ein aktuelle Liste an Tools, die unseren Studies bei SD helfen. Diese bitte erst mal hier als Linkliste rein packen und etwas strukturieren nach Themen/ Anwendung. Es geht nicht darum möglichst viele zu finden, sondern möglichst gute, z.B. um:
- Moodboards zu erstellen
- Schriften zu vergleichen
- Inspiration zu bekommen
- Semantische Differenziale zu erstellen
- Layoutbilder zu bekommen
- Blindtexte zu bekommen
- etc.

Hier schon mal ein Link:
https://medium.muz.li/the-best-free-design-tools-and-resources-for-designers-ddb8bb68a007

**Comment by cnoss** [comment]
<img width="511" alt="Bildschirmfoto 2022-08-29 um 11 35 25" src="https://user-images.githubusercontent.com/2807738/187171585-729fdb48-995f-4e3d-aac7-3b33f1e02109.png">

**Comment by calvinhnzr** [comment]
## 1. Moodboards

-   [Canva](https://www.canva.com/)
-   [Adobe Express](https://www.adobe.com/de/express/create/mood-board)

## 2. Schriften vergleichen

-   [Fontjoy](https://fontjoy.com/) (Aktuell nur mit Google Fonts)
-   [typeconnection](http://www.typeconnection.com/step1.php) (Man lernt wie man verschiedene Fonts miteinander paart)
-   [wordmark.it](https://wordmark.it/) (Sehr oberflächliche Funktionen, funktioiert mit installierten Schriften)

## 3. Inspiration

-   [Dribble](https://dribbble.com/)
-   [Behance](https://www.behance.net/)
-   [Awwwards](https://www.awwwards.com/)

## 4. Semantische Differenziale (Polaritätsprofil)

-   [Excel](https://www.microsoft.com/de-de/education/products/office)
-   [Tutorial](https://www.youtube.com/watch?v=tGlwuei87DQ)

## 5. Layoutbilder

#### Royalty Free

-   [Unsplash](https://unsplash.com/)
-   [Pexels](https://www.pexels.com/)
-   [Pixabay](https://pixabay.com/)
-   [Rawpixel](https://www.rawpixel.com/)
-   [Stocksnap](https://stocksnap.io/)

#### Rights Managed

-   [Adobe Stock](https://stock.adobe.com/)
-   [Shutter Stock](https://www.shutterstock.com/)

## 6. Blindtexte

-   [Blindtextgenerator](https://www.blindtextgenerator.de/)

## Sonstiges

-   [Framer](https://www.framer.com/) (Prototyping, Screendesign)

**Comment by calvinhnzr** [comment]
Eine erste Sammlung von Tools die ich gefunden habe bzw. selber ab und zu benutze.
Für Layoutbilder habe ich absichtlich ein paar mehrere Links rausgesucht, da ich oft das Problem habe nicht das passende Bild zu finden, wenn es Lizenzfrei sein soll.
Bis auf Excel habe ich leider noch keine Programm gefunden, welches Semantische Differenziale zuverlässig erstellt. Wahrscheinlich eignen sich aber auch Programme wie Figma, Illustrator oder Indesign dazu.

**Comment by cnoss** [comment]
@calvinhnzr cool – könntest Du die mal hier einbauen: https://th-koeln.github.io/mi-bachelor-screendesign/links/
