### ISSUE TITLE
Figma Tutorial(s) raussuchen und …

### ISSUE THREAD

**Issue by cnoss** [th-koeln/mi-bachelor-screendesign#7]
… [hier](https://github.com/th-koeln/mi-bachelor-screendesign/blob/master/index.md) verlinken.

**Comment by JulianSchoem** [comment]
Offizieller Figma Channel bei Youtube hat eine große Sammlung von Tutorials. Starten für Einsteiger und geben auch Tipps zum Designen, die außerhalb von Figma liegen (Google Fonts). 

https://www.youtube.com/channel/UCQsVmhSa4X-G3lHlUtejzLA

Linkeinbindung ist gepusht.
