### ISSUE TITLE
Ilias Kurs mal auf Verständlichkeit prüfen

### ISSUE THREAD

**Issue by cnoss** [th-koeln/mi-bachelor-screendesign#9]
Ist natürlich noch nicht komplett, aber die Struktur steht.
https://ilias.th-koeln.de/ilias.php?ref_id=1161102&mv=1&set_mode=flat&cmd=frameset&cmdClass=ilrepositorygui&cmdNode=u7&baseClass=ilRepositoryGUI

**Comment by JulianSchoem** [comment]
Korrekturgelesen und korrigiert.

Als Studierender bei WBA1 und GDVK war die github.io Seite immer perfekt um alle Informationen auf einen Blick zu haben und nicht im MI-Wiki, Ilias usw verschiedene Informationen zu finden. Aus diesem Grund würde ich es gut finden, wenn im Ilias nur kompakte Informationen zu finden sind. Also im Falle von Workshops nur Info zu Raum, freien Plätzen und Betreuer. Alle weiteren Informationen und Material sollte auf den github.io Seiten zu finden sein. Das Ilias sozusagen nur als Dateiablagen auf die von der github.io Seite verlinkt wird.

Statt dem Chat könnte man eventuell ein Forum integrieren. So wird es auch bei vielen anderen Modulen genutzt. Redundantes wird vermieden und es ist übersichtlicher.

**Comment by christianh92** [comment]
Habe noch einen Link korrigiert und finde das alles verständlich. 

Ansonsten sehe ich das ähnlich wie Julian. Ilias für die Orga und Github als eigentliche Wissensbasis. Im Forum könnte gezielter nach Topics gesucht werden. Bekommen wir im Chat oft die selben Fragen, müssten wir evtl. einen FAQ aufbauen?

**Comment by cnoss** [comment]
So isses auch gedacht … Forum: ok. bitte austauschen.

**Comment by christianh92** [comment]
Ist ausgetauscht.

**Comment by vschaefer** [comment]
Hmm irgendwie darf ich nichts ändern :(

- [ ] Der Chat müsste noch entfernt werden
- [ ] Der Link im Einführungstext muss noch angepasst werden:

**Comment by christianh92** [comment]
Ist auch erledigt
